import { Story } from "./types";

export const promStory: Story = {
  id: "ridgeview-prom-1987",
  title: "The Ridgeview Prom Night",
  year: "1987",
  setup:
    "Ridgeview High, May 22nd, 1987. Poppy Halloran left her house at 5:45pm to walk the six blocks down Maple Street to the Whitfield house for pre-prom photos. Her date, her friends, and both sets of parents were waiting on the Whitfields' front lawn with three cameras and a limo booked for 6:30. She never arrived. Twelve hours later a jogger found her prom corsage crushed on the shoulder of Maple Street, steps from her direct route. Read the evidence. Question the timeline. Crack the case.",
  characters: [
    {
      id: "poppy",
      name: "Poppy Halloran",
      role: "The victim — Ridgeview High senior",
      description:
        "Class treasurer, works weekends at the Dairy Freeze, on the prom queen ballot. Dating Jake Sorensen. Best friends with Amy Whitfield and Traci Nguyen since third grade.",
      isSuspect: false,
    },
    {
      id: "jake",
      name: "Jake Sorensen",
      role: "Poppy's boyfriend & prom date",
      description:
        "Point guard for the Ridgeview Rams. Was at the Whitfield house from 5:50pm on, waiting with everyone else.",
      isSuspect: true,
    },
    {
      id: "amy",
      name: "Amy Whitfield",
      role: "Poppy's best friend — also on the prom queen ballot",
      description:
        "Hosted photos at her house because her parents have the big front lawn and her dad likes to film everything on his new camcorder. Also up for prom queen tonight.",
      isSuspect: true,
    },
    {
      id: "denise",
      name: "Denise Whitfield",
      role: "Amy's mother, hosting parent",
      description:
        "Ridgeview High class of '63 — and 1963's prom queen, a fact she brings up often. Spent the afternoon 'getting everything ready' for the parents' after-photos get-together.",
      isSuspect: true,
    },
    {
      id: "frank",
      name: "Frank Whitfield",
      role: "Amy's father, hosting parent",
      description:
        "Sells insurance, just bought the family a Prodigy home computer service subscription and won't stop talking about it. Manned the camcorder on the lawn all evening.",
      isSuspect: true,
    },
    {
      id: "traci",
      name: "Traci Nguyen",
      role: "Poppy's other best friend",
      description: "Yearbook photo editor. Arrived at the Whitfields' at 5:55pm with Marcus.",
      isSuspect: true,
    },
    {
      id: "marcus",
      name: "Marcus Webb",
      role: "Traci's date",
      description: "Works with Jake at the Amoco station on weekends. Drove Traci over himself.",
      isSuspect: true,
    },
    {
      id: "carol",
      name: "Carol Halloran",
      role: "Poppy's mother",
      description:
        "Took photos of Poppy alone on the porch before she left for the Whitfields'. Arrived at the Whitfields' at 6:15pm with Richard, expecting Poppy to already be there.",
      isSuspect: false,
    },
    {
      id: "richard",
      name: "Richard Halloran",
      role: "Poppy's father",
      description: "Split the limo cost with the Whitfields over the Prodigy mail service that week.",
      isSuspect: false,
    },
    {
      id: "lou",
      name: "Lou Griggs",
      role: "Limo driver, Griggs Livery",
      description: "Booked for 6:30pm pickup at the Whitfield house. Arrived on time and waited.",
      isSuspect: false,
    },
    {
      id: "kowalski",
      name: "Principal Ed Kowalski",
      role: "Principal, Ridgeview High School",
      description: "Ran the prom court voting this year, same as every year. Well-liked, well-known for staying out of student drama.",
      isSuspect: false,
    },
  ],
  evidence: [
    {
      id: "email-dresses",
      category: "correspondence",
      title: "\"PROM SQUAD 87\" — Group Text",
      subtitle: "Poppy, Amy & Traci",
      date: "May 1, 1987 — 8:41pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Poppy H.", time: "8:41pm", text: "ok the dress is TOTALLY hemmed. Mrs. Alvarez did the beading by hand, it is stunning" },
        { from: "Traci N.", time: "8:44pm", text: "So cool! mine came in today too. the shoes are almost a full size too big but whatever, im wearing two pairs of socks, problem solved" },
        { from: "Amy W.", time: "8:47pm", text: "I thought I was excited. But my mom is already rearranging the whole living room for pictures. she's been planning the \"photo wall\" since March. Its all she talks about" },
        { from: "Poppy H.", time: "8:52pm", text: "Well the photos will be stellar then! And not to jinx it or anything but i really want to win queen tonight." },
        { from: "Amy W.", time: "8:53pm", text: "shut up, dont jinx it! I think you will win. My mom keeps asking me who I think will win and I told her it has to be you. She wanted me to make POSTERS to try to win myself. Could you imagine? As if." },
        { from: "Traci N.", time: "8:55pm", text: "you're both gonna win something, quit stressing. see you guys tomorrow at school." },
      ],
    },
    {
      id: "text-traci-doubts",
      category: "correspondence",
      title: "Text Messages — Traci (private)",
      subtitle: "Poppy & Traci Nguyen",
      date: "May 15, 1987 — 9:40pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Poppy H.", time: "9:40pm", text: "ok can i vent. Jake flaked on me again tonight. said he had to hang out with the guys from the team, AGAIN. thats like the third time this month" },
        { from: "Traci N.", time: "9:42pm", text: "wait, seriously? that's so bogus, i thought you two were solid" },
        { from: "Poppy H.", time: "9:44pm", text: "i thought so too. its always some football thing now that theyre gearing up for summer training. i dunno, its starting to feel like im just an afterthought" },
        { from: "Traci N.", time: "9:46pm", text: "have you told him how you feel or are you just gonna stew about it" },
        { from: "Poppy H.", time: "9:49pm", text: "i brought it up once and he said i was overreacting. honestly, im kind of over it. i think im gonna end things" },
        { from: "Traci N.", time: "9:50pm", text: "oh wow, its that bad? when?" },
        { from: "Poppy H.", time: "9:53pm", text: "Yes seriously. Everytime I bring it up its a screaming fight, and thats not what I want." },
        { from: "Poppy H.", time: "9:54pm", text: "But not yet. i dont want the whole prom thing turning into a big dramatic mess right before. im gonna get through saturday and have the talk with him after. one nice night first, then im done" },
        { from: "Traci N.", time: "9:55pm", text: "that's probably smart, actually. i wont say anything, promise. you're allowed to have one good night" },
        { from: "Poppy H.", time: "9:57pm", text: "thanks. dont tell amy yet either, she'll want to make it a whole thing" },
        { from: "Traci N.", time: "9:58pm", text: "lips sealed." },
      ],
    },
    {
      id: "email-jake",
      category: "correspondence",
      title: "Text Messages — Jake",
      subtitle: "Poppy & Jake Sorensen",
      date: "May 21, 1987 — 9:12pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Jake S.", time: "9:12pm", text: "hey what time am i supposed to be at the whitfields tomorrow" },
        { from: "Poppy H.", time: "9:15pm", text: "Were all meeting at 5:30. photos start at 6, limo comes at 6:30. dont forget the corsage, its in the fridge at the market under your name" },
        { from: "Jake S.", time: "9:16pm", text: "got it. corsage is the peach one right, matches your dress" },
        { from: "Poppy H.", time: "9:17pm", text: "yes! im leaving my house around 5:45 to walk over, dont be late mr sorensen" },
        { from: "Jake S.", time: "9:19pm", text: "i wont i wont, promise. see you tomorrow" },
      ],
    },
    {
      id: "email-parents",
      category: "correspondence",
      title: "Text Messages — The Parents",
      subtitle: "Carol Halloran & Denise Whitfield",
      date: "May 19, 1987 — 2:03pm",
      threadOwner: "Carol H.",
      thread: [
        { from: "Carol H.", time: "2:03pm", text: "Denise, Richard spoke to Lou, the limo for the six of them comes to $95 for the evening, split down the middle that's $47.50 each. Does that work?" },
        { from: "Denise W.", time: "2:20pm", text: "That's fine, I'll have Frank write the check. Are we still doing drinks for the grown-ups after the photos? I can pick up potato skins from Rusty's on my way back from the beauty parlor, and I make a wonderful cosmopolitan if I do say so myself." },
        { from: "Carol H.", time: "2:25pm", text: "That sounds lovely. Richard is bringing the good camera so let's get everyone on the lawn by 6 sharp before the light goes." },
        { from: "Denise W.", time: "2:31pm", text: "Perfect. I'm so excited for the girls! The BIG night!" },
      ],
    },
    {
      id: "photo-driveway",
      category: "photograph",
      title: "Driveway Photos, No Poppy",
      subtitle: "Taken by Richard Halloran on the Whitfields' front lawn, 6:38pm",
      date: "May 22, 1987 — 6:38pm",
      photo: {
        scene: "driveway",
        imageUrl: "/crack-the-case/evidence/driveway.png",
        note: "Denise Whitfield is not in this photo. Her Buick sits in the background — plate OH 4J-71 visible over the hood.",
      },
    },
    {
      id: "photo-porch",
      category: "photograph",
      title: "Poppy, Alone in Her Dress",
      subtitle: "Taken by Carol Halloran on the Hallorans' front porch, 5:40pm",
      date: "May 22, 1987 — 5:40pm",
      photo: {
        scene: "porch",
        imageUrl: "/crack-the-case/evidence/porch.png",
        note: "Timestamped 5:40pm on the back, in Carol's handwriting, moments before Poppy left for the Whitfields'. The box in her hands is a visual match for the crushed one later found on Maple Street.",
      },
    },
    {
      id: "photo-trafficcam",
      category: "photograph",
      title: "Cameras 12, 7 & 3 — Sequential Frames",
      subtitle: "Ridgeview PD street cameras along Maple, released to investigators",
      date: "May 22, 1987 — 6:03pm to 6:06pm",
      photo: {
        scene: "traffic-cam",
        imageUrl: "/crack-the-case/evidence/traffic-cam.png",
        note: "Cam 12 and Cam 7 both show Poppy walking alone toward Maple, a dark sedan easing up behind her in the Cam 7 frame. By Cam 3, ninety seconds later, the road is empty except for the car idling near the treeline — and a small pale object dropped on the shoulder where she should have been walking. (Ridgeview PD confirms the onboard date stamps on these cameras are known to run wrong — the frames are from the evening of the 22nd despite the overlay.)",
      },
    },
    {
      id: "town-map",
      category: "photograph",
      title: "Ridgeview — Town Map & Camera Locations",
      subtitle: "Marked up by Ridgeview PD, showing Poppy's route and Cams 12, 7 & 3",
      date: "May 23, 1987",
      photo: {
        scene: "map",
        imageUrl: "/crack-the-case/evidence/map.png",
        note: "Poppy's direct route from her house to the Whitfields' runs straight down Maple. Rusty's Pub & Grub sits just a short detour off that same route — well within a fifteen-minute round trip.",
      },
    },
    {
      id: "photo-crimescene",
      category: "photograph",
      title: "Maple Street — Scene Photos",
      subtitle: "Taken by Ridgeview PD the following morning",
      date: "May 23, 1987 — 7:15am",
      photo: {
        scene: "crime-scene",
        imageUrl: "/crack-the-case/evidence/crime-scene.png",
        note: "Evidence markers 1, 3, 5 and 7 mark the crushed corsage box, a scrap of blue fabric, a cigarette butt, and a partial shoe print — none of Poppy's friends or family admit to smoking. Evidence tech's read on the faint tread nearby: consistent with a full-size sedan tire, not a compact car.",
      },
    },
    {
      id: "prom-night",
      category: "photograph",
      title: "Prom Night Goes On",
      subtitle: "Taken outside Ridgeview High, roughly 9:30pm",
      date: "May 22, 1987 — 9:30pm",
      photo: {
        scene: "school",
        imageUrl: "/crack-the-case/evidence/school.png",
        note: "While Poppy's friends stayed behind searching, the dance went on without them. A Rams player in a letterman jacket arrives alone in the rain, hours after kickoff for the pre-photos — around the same time Jake's teammates would have been getting to the gym.",
      },
    },
    {
      id: "photo-promphotos",
      category: "photograph",
      title: "Waiting on the Whitfields' Kitchen",
      subtitle: "Taken by Frank Whitfield's camcorder, shortly after 6pm",
      date: "May 22, 1987 — 6:10pm",
      photo: {
        scene: "prom-photo",
        imageUrl: "/crack-the-case/evidence/prom-photo.png",
        note: "Denise told police she 'never really left the house' that afternoon — but the spread was already out and the pitcher already poured well before anyone started asking where Poppy was.",
      },
    },
    {
      id: "transcript-denise",
      category: "transcript",
      title: "Interrogation — Denise Whitfield",
      subtitle: "Amy's mother, hosting parent",
      date: "May 24, 1987",
      transcript: {
        subject: "Denise Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Thank you for coming in, Mrs. Whitfield. Walk me through your afternoon." },
          { speaker: "Denise", text: "I was in and out of the kitchen all afternoon getting things ready for after the photos. I never really left the house." },
          { speaker: "Okafor", text: "Never left the house at all, between noon and when Poppy was expected?" },
          { speaker: "Denise", text: "That's right. I had far too much to do. Amy can tell you, I was a whirlwind in that kitchen." },
          { speaker: "Okafor", text: "And were you close with Poppy?" },
          { speaker: "Denise", text: "Of course. She practically grew up in my kitchen, same as Traci. Sweet girl. This whole thing is a nightmare, I haven't slept." },
          { speaker: "Okafor", text: "Were you excited for the night? Prom, the pictures, all of it." },
          { speaker: "Denise", text: "I — yes, of course. Why wouldn't I be." },
          { speaker: "Okafor", text: "You hesitated." },
          { speaker: "Denise", text: "It just feels strange to say I was excited, given how the night ended. I don't want that to sound wrong. I meant I was excited for Amy — it's her senior prom, I wanted it to be perfect for her. That's all I meant." },
        ],
      },
    },
    {
      id: "transcript-frank",
      category: "transcript",
      title: "Interrogation — Frank Whitfield",
      subtitle: "Amy's father, hosting parent",
      date: "May 24, 1987",
      transcript: {
        subject: "Frank Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Where were you the day of the dance, Mr. Whitfield?" },
          { speaker: "Frank", text: "In the garage most of the afternoon, honestly. Tinkering with the lawnmower, mostly just staying out from underfoot. Denise likes to run the show when she's hosting, and she's been a little intense these last few months. Best to let her have the house." },
          { speaker: "Okafor", text: "Intense how?" },
          { speaker: "Frank", text: "Just moody. On edge about little things, like the dust on the skirting boards. Things like that." },
          { speaker: "Okafor", text: "So you weren't with her or your daughter that afternoon." },
          { speaker: "Frank", text: "No, not really, not till everyone started showing up around five-thirty. Then I had the camcorder out and I was filming the whole thing — got it all on tape, if you want it." },
          { speaker: "Okafor", text: "Did anyone seem out of the ordinary?" },
          { speaker: "Frank", text: "Honestly I had the camcorder up to my face most of that time, I wasn't paying close attention. It was a big night, everybody was a little keyed up." },
          { speaker: "Okafor", text: "How would you describe your relationship with Poppy?" },
          { speaker: "Frank", text: "Fond of her, same as any of Amy's friends. She is a good kid. Or was a good kid, sorry sir." },
          { speaker: "Okafor", text: "Is there anything else that stands out from that day?" },
          { speaker: "Frank", text: "Not really. We were all just pretty panicked once Poppy's parents got there before her." },
        ],
      },
    },
    {
      id: "transcript-amy",
      category: "transcript",
      title: "Interrogation — Amy Whitfield",
      subtitle: "Poppy's best friend",
      date: "May 24, 1987",
      transcript: {
        subject: "Amy Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "How was Poppy seeming this week, anything unusual?" },
          { speaker: "Amy", text: "No, she was just excited. We all were. I keep thinking about how much we spoke about prom night, ever since we were freshmen." },
          { speaker: "Okafor", text: "You two were both up for prom queen tonight. Was there any tension about that?" },
          { speaker: "Amy", text: "No! God, no. I mean, we both said we wanted it, but it was a joke, kind of. We weren't going to let a stupid crown mess up our friendship. I don't even care that much." },
          { speaker: "Okafor", text: "And how was her relationship with her boyfriend?" },
          { speaker: "Amy", text: "Good — great, as far as I know. Everybody loved them together." },
          { speaker: "Okafor", text: "Did you notice anyone acting strange?" },
          { speaker: "Amy", text: "No. Everyone felt genuinely scared when we realized she didn't make it. Her boyfriend even started running the route she took to try and find her. It was like a nightmare." },
          { speaker: "Okafor", text: "Is there anything else you remember from that night that felt off, even something small?" },
          { speaker: "Amy", text: "I keep thinking about it and I don't — I don't want to say something that isn't fair to her. She's my mom. Can I go now?" },
        ],
      },
    },
    {
      id: "transcript-jake",
      category: "transcript",
      title: "Interrogation — Jake Sorensen",
      subtitle: "Poppy's boyfriend",
      date: "May 24, 1987",
      transcript: {
        subject: "Jake Sorensen",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "What time did you get to the Whitfields'?" },
          { speaker: "Jake", text: "5:50, maybe a couple minutes before. I have three witnesses, we were all just standing around waiting." },
          { speaker: "Okafor", text: "Did you leave at any point, for any reason?" },
          { speaker: "Jake", text: "No, never. I was there the whole time, ask anybody." },
          { speaker: "Okafor", text: "How long have you and Poppy been together?" },
          { speaker: "Jake", text: "Since sophomore year. Almost two years. I had her corsage picked out weeks ago, the peach one, I wanted it to match exactly." },
          { speaker: "Okafor", text: "Did anything seem different about her lately? Any arguments, anyone bothering her?" },
          { speaker: "Jake", text: "No, nothing like that. Everybody loved Poppy. She was excited about tonight, we both were." },
          { speaker: "Okafor", text: "Is there anything else you can think of, even something that seemed small at the time?" },
          { speaker: "Jake", text: "I keep thinking if I'd walked over and met her partway none of this would've happened. I keep going over it and I can't — I just want to know what happened to her." },
          { speaker: "Okafor", text: "What went through your mind when you realized she wasn't coming?" },
          { speaker: "Jake", text: "I honestly didn't think something bad happened at first. It wasn't until all the parents started to panic that I realized she could've been hurt. That was the worst case scenario in my mind, she fell or something." },
          { speaker: "Okafor", text: "Anything else you want to share?" },
          { speaker: "Jake", text: "No. I just miss her." },
        ],
      },
    },
    {
      id: "transcript-traci",
      category: "transcript",
      title: "Interrogation — Traci Nguyen",
      subtitle: "Poppy's best friend",
      date: "May 24, 1987",
      transcript: {
        subject: "Traci Nguyen",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "What time did you arrive at the Whitfield home that day?" },
          { speaker: "Traci", text: "I can't remember exactly, the same time as everyone else." },
          { speaker: "Okafor", text: "Anything odd about the Whitfield house that evening?" },
          { speaker: "Traci", text: "No, everything seemed normal." },
          { speaker: "Okafor", text: "And what do you think about Poppy's boyfriend?" },
          { speaker: "Traci", text: "I mean. They're happy." },
          { speaker: "Okafor", text: "You don't sound so sure." },
          { speaker: "Traci", text: "I just don't want it to sound like he did anything bad. They had some fights recently. But it wasn't anything serious." },
          { speaker: "Okafor", text: "Look Traci, if something happened you should tell us. Even if it doesn't seem possible." },
          { speaker: "Traci", text: "They were fighting about stupid stuff, like him cancelling on her dates a lot. She was thinking about breaking up with him, but she was still looking forward to prom." },
          { speaker: "Okafor", text: "What time did he arrive at photos?" },
          { speaker: "Traci", text: "About 6pm? He was late as usual." },
        ],
      },
    },
    {
      id: "transcript-marcus",
      category: "transcript",
      title: "Interrogation — Marcus Webb",
      subtitle: "Traci's date",
      date: "May 24, 1987",
      transcript: {
        subject: "Marcus Webb",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Where were you the whole evening?" },
          { speaker: "Marcus", text: "Well before meeting for photos, I was at the school gym with some friends. Then I got to the Whitfields around 5:45." },
          { speaker: "Okafor", text: "Was Jake with you the entire time, no gaps?" },
          { speaker: "Marcus", text: "The whole time, yeah. We were talking about the game Friday, then about work, killing time. He never went anywhere." },
          { speaker: "Okafor", text: "Did he get there at the same time as you?" },
          { speaker: "Marcus", text: "No, he was running late. I think something about the corsage." },
          { speaker: "Okafor", text: "Do you know where he got the corsage?" },
          { speaker: "Marcus", text: "He never told me, but most people get it at the market. So he wouldn't have been too far from the house." },
          { speaker: "Okafor", text: "And how did you think their relationship was?" },
          { speaker: "Marcus", text: "Amazing. Everybody wanted a girl like Poppy." },
        ],
      },
    },
    {
      id: "transcript-hallorans",
      category: "transcript",
      title: "Interrogation — Carol & Richard Halloran",
      subtitle: "Poppy's parents",
      date: "May 24, 1987",
      transcript: {
        subject: "Carol & Richard Halloran",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Take me through your daughter's last known movements, from your side." },
          { speaker: "Carol", text: "She left our house at 5:40 sharp, I have the photo timestamped. It's a five minute walk to the Whitfields', she'd done it a hundred times, that whole route, she knew it like the back of her hand. She should have been there far before us." },
          { speaker: "Richard", text: "We got there at 6:15 to take a few pictures with the kids and she still wasn't there. It wasn't like Poppy to be late." },
          { speaker: "Okafor", text: "Did Poppy have any reason to take a different route that evening, or stop anywhere along the way?" },
          { speaker: "Carol", text: "None that I know of. She was so excited, she wanted to get there early, she'd been talking about tonight for weeks. She wouldn't have wandered off." },
          { speaker: "Richard", text: "She wasn't the type to just not show up somewhere. If she was going to be late she'd stop somewhere and call. That's what scared us the second we realized how much time had passed." },
          { speaker: "Okafor", text: "How would you describe the Whitfields, and your relationship with them?" },
          { speaker: "Carol", text: "We've known Denise and Frank for years, since the girls were little." },
          { speaker: "Okafor", text: "Is there anything else, however small, that's stuck with you since that night?" },
          { speaker: "Richard", text: "No. We just want some justice." },
        ],
      },
    },
    {
      id: "transcript-principal",
      category: "transcript",
      title: "Interrogation — Principal Kowalski",
      subtitle: "Ridgeview High School",
      date: "May 25, 1987",
      transcript: {
        subject: "Principal Ed Kowalski",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "How well did you know Poppy Halloran?" },
          { speaker: "Kowalski", text: "As well as a principal knows any good student, I'd say. Class treasurer, never a single discipline issue in four years. This whole school is shaken up about it." },
          { speaker: "Okafor", text: "What can you tell me about the group of kids she ran with?" },
          { speaker: "Kowalski", text: "Good kids, all of them. Traci's on the yearbook staff, sharp girl. Amy Whitfield's in student council, very involved. Jake Sorensen's one of our better ballplayers, and frankly one of the more level-headed kids on that team." },
          { speaker: "Okafor", text: "I have to ask about the boyfriend. Anything about him give you pause?" },
          { speaker: "Kowalski", text: "Jake? No, absolutely not. I'd stake my job on that kid. Good student, good player, the kind of kid teachers actually like having in class. Honestly, I had money on the two of them for king and queen tonight, if you want the truth." },
          { speaker: "Okafor", text: "Were they well liked, generally? Any friction with other students?" },
          { speaker: "Kowalski", text: "Both of them, very well liked. By everyone, as far as I ever saw." },
          { speaker: "Okafor", text: "Anything at all stand out to you, even something that seemed minor at the time?" },
          { speaker: "Kowalski", text: "Well — this is probably nothing, but Denise Whitfield came by my office a few times this spring, asking how the prom court voting works. Wanted to know if there was any way to, her words, 'help things along' for Amy. Offered a pretty generous donation to the school activities fund, if it would help her daughter's chances." },
          { speaker: "Okafor", text: "What did you tell her?" },
          { speaker: "Kowalski", text: "Told her the voting's done by the student body, sealed ballots, nothing I or anyone else touches. Turned down the donation on the spot, obviously. She seemed embarrassed, apologized, and I never heard another word about it. Didn't think much of it at the time — parents get like that about this stuff sometimes." },
        ],
      },
    },
  ],
  solutionCharacterId: "denise",
  solutionSummary:
    "It was Denise Whitfield. She left the house around 5:48 to pick up potato skins from Rusty's — and passed Poppy walking down Maple Street. Prom queen wasn't a joke to Denise; Principal Kowalski's account of her quietly trying to buy influence over the vote for Amy shows just how far that obsession went. Seeing Poppy — a genuine threat to Amy's shot at the crown — walking alone on the road, something in Denise snapped. She swerved onto the shoulder as she passed her, striking Poppy and killing her. She panicked, drove on to Rusty's as if nothing happened to establish her alibi, came home, plated the potato skins she'd already bought, and told police she'd 'never really left the house.' The sedan in the traffic-cam frames, the tire track at the crime scene, the potato skins already out in the kitchen photo taken well before anyone started asking where Poppy was, and her own thin, evasive answers about that night all place her on Maple Street at 6:05pm — minutes after Poppy was last seen alive.",
};
