import { Story } from "./types";

export const promStory: Story = {
  id: "ridgeview-prom-1987",
  title: "The Ridgeview Prom Night",
  year: "1987",
  setup:
    "Ridgeview High, May 22nd, 1987. Poppy Halloran left her house at 5:45pm to walk the six blocks to the Whitfield house for pre-prom photos. Her date, her friends, and both sets of parents were waiting on the Whitfields' front lawn with three cameras and a limo booked for 6:30. She never arrived. Twelve hours later a jogger found her prom corsage crushed on the shoulder of Culvert Road, a half mile off her route. Read the evidence. Question the timeline. Crack the case.",
  characters: [
    {
      id: "poppy",
      name: "Poppy Halloran",
      role: "The victim — Ridgeview High senior",
      description:
        "Class treasurer, works weekends at the Dairy Freeze, on the prom queen ballot. Dating Jake Sorensen. Best friends with Amy Whitfield and Traci Nguyen since third grade.",
      isSuspect: false,
    },
    {
      id: "jake",
      name: "Jake Sorensen",
      role: "Poppy's boyfriend & prom date",
      description:
        "Point guard for the Ridgeview Rams. Was at the Whitfield house from 5:50pm on, waiting with everyone else.",
      isSuspect: true,
    },
    {
      id: "amy",
      name: "Amy Whitfield",
      role: "Poppy's best friend — also on the prom queen ballot",
      description:
        "Hosted photos at her house because her parents have the big front lawn and her dad likes to film everything on his new camcorder. Also up for prom queen tonight.",
      isSuspect: true,
    },
    {
      id: "denise",
      name: "Denise Whitfield",
      role: "Amy's mother, hosting parent",
      description:
        "Ridgeview High class of '63 — and 1963's prom queen, a fact she brings up often. Spent the afternoon 'getting everything ready' for the parents' after-photos get-together.",
      isSuspect: true,
    },
    {
      id: "frank",
      name: "Frank Whitfield",
      role: "Amy's father, hosting parent",
      description:
        "Sells insurance, just bought the family a Prodigy home computer service subscription and won't stop talking about it. Manned the camcorder on the lawn all evening.",
      isSuspect: true,
    },
    {
      id: "traci",
      name: "Traci Nguyen",
      role: "Poppy's other best friend",
      description: "Yearbook photo editor. Arrived at the Whitfields' at 5:55pm with Marcus.",
      isSuspect: true,
    },
    {
      id: "marcus",
      name: "Marcus Webb",
      role: "Traci's date",
      description: "Works with Jake at the Amoco station on weekends. Drove Traci over himself.",
      isSuspect: true,
    },
    {
      id: "ben",
      name: "Ben Cole",
      role: "Amy's date",
      description: "New to Ridgeview this year, transferred in January. Doesn't know Poppy well.",
      isSuspect: true,
    },
    {
      id: "carol",
      name: "Carol Halloran",
      role: "Poppy's mother",
      description:
        "Took photos of Poppy alone in the driveway before she left for the Whitfields'. Arrived at the Whitfields' at 6:15pm with Richard, expecting Poppy to already be there.",
      isSuspect: false,
    },
    {
      id: "richard",
      name: "Richard Halloran",
      role: "Poppy's father",
      description: "Split the limo cost with the Whitfields over the Prodigy mail service that week.",
      isSuspect: false,
    },
    {
      id: "lou",
      name: "Lou Griggs",
      role: "Limo driver, Griggs Livery",
      description: "Booked for 6:30pm pickup at the Whitfield house. Arrived on time and waited.",
      isSuspect: false,
    },
  ],
  evidence: [
    {
      id: "email-dresses",
      category: "correspondence",
      title: "\"PROM SQUAD 87\" — Group Text",
      subtitle: "Poppy, Amy & Traci",
      date: "May 18, 1987 — 8:41pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Poppy H.", time: "8:41pm", text: "ok the dress is TOTALLY hemmed. Mrs. Alvarez did the beading by hand, i could just die, its so good" },
        { from: "Traci N.", time: "8:44pm", text: "no way, mine came in today too. the shoes are like a full size too big but whatever, im wearing two pairs of socks, problem solved" },
        { from: "Amy W.", time: "8:47pm", text: "you guys my mom is already rearranging the whole living room for pictures. she's been planning the \"photo wall\" since March, i am not even joking" },
        { from: "Poppy H.", time: "8:52pm", text: "ok not to jinx it or anything but... i kinda really want to win queen tonight. dont hate me" },
        { from: "Amy W.", time: "8:53pm", text: "shut up, dont jinx it! but also, same, honestly. i mean i wouldnt be mad if i won either, my mom won back in 63 and she brings it up constantly, it would totally make her year" },
        { from: "Traci N.", time: "8:55pm", text: "you're both gonna win something, quit stressing. see you guys at my house at 5:30 tomorrow for hair" },
      ],
    },
    {
      id: "text-traci-doubts",
      category: "correspondence",
      title: "Text Messages — Traci (private)",
      subtitle: "Poppy & Traci Nguyen",
      date: "May 15, 1987 — 9:40pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Poppy H.", time: "9:40pm", text: "ok can i vent for a sec. jake bailed on me again tonight. said he had to hang out with the guys from the team, AGAIN. thats like the third time this month" },
        { from: "Traci N.", time: "9:42pm", text: "wait, seriously? that's so bogus, i thought you two were solid" },
        { from: "Poppy H.", time: "9:44pm", text: "i thought so too. its always some football thing now that theyre gearing up for summer league. i dunno, its starting to feel like im just an afterthought" },
        { from: "Traci N.", time: "9:46pm", text: "have you told him how you feel or are you just gonna stew about it" },
        { from: "Poppy H.", time: "9:49pm", text: "i brought it up once and he said i was overreacting. honestly, im kind of over it. i think im gonna end things" },
        { from: "Traci N.", time: "9:50pm", text: "oh wow, ok. when" },
        { from: "Poppy H.", time: "9:53pm", text: "not yet. i dont want the whole prom thing turning into a big dramatic mess right before. im gonna get through saturday and have the talk with him after. one nice night first, then im done" },
        { from: "Traci N.", time: "9:55pm", text: "that's probably smart, actually. i wont say anything, promise. you're allowed to have one good night" },
        { from: "Poppy H.", time: "9:57pm", text: "thanks. dont tell amy yet either, she'll want to make it a whole thing" },
        { from: "Traci N.", time: "9:58pm", text: "lips sealed. love you, get some sleep" },
      ],
    },
    {
      id: "email-jake",
      category: "correspondence",
      title: "Text Messages — Jake",
      subtitle: "Poppy & Jake Sorensen",
      date: "May 21, 1987 — 9:12pm",
      threadOwner: "Poppy H.",
      thread: [
        { from: "Jake S.", time: "9:12pm", text: "hey what time am i supposed to be at the whitfields tomorrow" },
        { from: "Poppy H.", time: "9:15pm", text: "photos start at 6, limo comes at 6:30. dont forget the boutonniere, its in the fridge at the flower shop under your name" },
        { from: "Jake S.", time: "9:16pm", text: "got it. corsage is the peach one right, matches your dress" },
        { from: "Poppy H.", time: "9:17pm", text: "yes! ok i have to go finish my nails. im leaving my house around 5:45 to walk over, dont be late mr sorensen" },
        { from: "Jake S.", time: "9:19pm", text: "i wont, promise. see you tomorrow" },
      ],
    },
    {
      id: "email-parents",
      category: "correspondence",
      title: "Text Messages — The Parents",
      subtitle: "Carol Halloran & Denise Whitfield",
      date: "May 19, 1987 — 2:03pm",
      threadOwner: "Carol H.",
      thread: [
        { from: "Carol H.", time: "2:03pm", text: "Denise, Richard spoke to Lou at Griggs Livery, the limo for the six of them comes to $95 for the evening, split down the middle that's $47.50 each. Does that work?" },
        { from: "Denise W.", time: "2:20pm", text: "That's fine, I'll have Frank write the check. Are we still doing drinks for the grown-ups after the photos? I can pick up potato skins from Rusty's on my way back from the beauty parlor, and I make a wonderful cosmopolitan if I do say so myself." },
        { from: "Carol H.", time: "2:25pm", text: "That sounds lovely. Richard is bringing the good camera so let's get everyone on the lawn by 6 sharp before the light goes." },
        { from: "Denise W.", time: "2:31pm", text: "Perfect. I already told Amy that lawn is MINE for the evening, ha! See you both tomorrow." },
      ],
    },
    {
      id: "email-whereisshe",
      category: "correspondence",
      title: "Group Text — \"where is she??\"",
      subtitle: "Amy, Traci, Jake, Marcus & Ben",
      date: "May 22, 1987 — 6:04pm to 6:52pm",
      threadOwner: "Jake S.",
      thread: [
        { from: "Amy W.", time: "6:04pm", text: "is poppy with anyone? she's not here yet" },
        { from: "Traci N.", time: "6:11pm", text: "no, i thought she left her house already? jake are you at the whitfields" },
        { from: "Jake S.", time: "6:15pm", text: "yeah been here since 550, no sign of her. tried calling her house, no answer" },
        { from: "Marcus W.", time: "6:22pm", text: "amy's mom seems kind of frazzled, not gonna lie, she keeps going in and out checking the driveway" },
        { from: "Ben C.", time: "6:30pm", text: "limo guy is here, he's just waiting in the driveway" },
        { from: "Amy W.", time: "6:41pm", text: "my mom just got back from running an errand and still no poppy. this isnt like her at all" },
        { from: "Jake S.", time: "6:52pm", text: "poppys parents just pulled up, her mom is freaking out, we're calling the police" },
      ],
    },
    {
      id: "photo-driveway",
      category: "photograph",
      title: "Driveway Photos, No Poppy",
      subtitle: "Taken by Richard Halloran on the Whitfields' front lawn, 6:38pm",
      date: "May 22, 1987 — 6:38pm",
      photo: {
        scene: "driveway",
        note: "Denise Whitfield is not in this photo. Frank says she'd 'just stepped inside.'",
      },
    },
    {
      id: "photo-porch",
      category: "photograph",
      title: "Poppy, Alone in Her Dress",
      subtitle: "Taken by Carol Halloran on the Hallorans' front porch, 5:40pm",
      date: "May 22, 1987 — 5:40pm",
      photo: {
        scene: "porch",
        note: "Timestamped 5:40pm on the back, in Carol's handwriting — five minutes before Poppy left for the Whitfields'.",
      },
    },
    {
      id: "photo-trafficcam",
      category: "photograph",
      title: "Elm & 4th Traffic Camera — Sequential Frames",
      subtitle: "Ridgeview PD intersection camera, released to investigators",
      date: "May 22, 1987 — 5:49pm to 5:52pm",
      photo: {
        scene: "traffic-cam",
        note: "Three sequential frames: Poppy walking, then a station wagon idling half a block behind her at the Elm stop sign, then both gone from the next frame. Elm & 4th is two blocks off Poppy's direct route to the Whitfields' — and directly on the road to Rusty's Pub & Grub.",
      },
    },
    {
      id: "photo-crimescene",
      category: "photograph",
      title: "Culvert Road — Scene Photos",
      subtitle: "Taken by Ridgeview PD the following morning",
      date: "May 23, 1987 — 7:15am",
      photo: {
        scene: "crime-scene",
        note: "Evidence tech's read on the tread: consistent with a full-size wagon tire, not a compact car.",
      },
    },
    {
      id: "photo-promphotos",
      category: "photograph",
      title: "Prom Photos, Later That Night",
      subtitle: "Taken by Frank Whitfield's camcorder, after the search began",
      date: "May 22, 1987 — 9:10pm",
      photo: {
        scene: "prom-photo",
        note: "Denise told police she 'never left the kitchen all evening' and 'didn't have time to make anything special' once Poppy went missing.",
      },
    },
    {
      id: "transcript-denise",
      category: "transcript",
      title: "Interrogation — Denise Whitfield",
      subtitle: "Amy's mother, hosting parent",
      date: "May 24, 1987",
      transcript: {
        subject: "Denise Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Thank you for coming in, Mrs. Whitfield. Walk me through your afternoon." },
          { speaker: "Denise", text: "I was in and out of the kitchen all afternoon getting things ready for after the photos. I never really left the house." },
          { speaker: "Okafor", text: "Never left the house at all, between noon and when Poppy was expected?" },
          { speaker: "Denise", text: "That's right. I had far too much to do. Amy can tell you, I was a whirlwind in that kitchen." },
          { speaker: "Okafor", text: "You hosted the photos this year. That must have meant a lot to you, given your own history with prom." },
          { speaker: "Denise", text: "I don't see what that has to do with anything, Detective, but yes. Hosting is a lovely tradition. I wanted the girls to have a beautiful evening." },
          { speaker: "Okafor", text: "Were you close with Poppy?" },
          { speaker: "Denise", text: "Of course. She practically grew up in my kitchen, same as Traci. Sweet girl. This whole thing is a nightmare, I haven't slept." },
          { speaker: "Okafor", text: "And the car in your driveway in the 6:38 photo — Richard Halloran's photo shows it parked at an angle, like it had just pulled in." },
          { speaker: "Denise", text: "I'm sure I don't know what you mean. Frank moves that car around the driveway all the time, backing it in, pulling it out, he's forever rearranging things for his filming angles." },
          { speaker: "Okafor", text: "One more thing. Frank mentioned you 'stepped out' around six. Where did you go?" },
          { speaker: "Denise", text: "I really don't remember stepping out. It was such a chaotic evening, Detective, everyone was frantic." },
          { speaker: "Okafor", text: "Your husband seemed fairly certain. He said Rusty's, for the potato skins you two discussed with the Hallorans." },
          { speaker: "Denise", text: "Well, if Frank says so. I truly can't account for every minute, I was hosting six teenagers and two other sets of parents. Is this really necessary right now, with that poor girl still missing?" },
          { speaker: "Okafor", text: "Just trying to get a clear picture, Mrs. Whitfield. We'll be in touch if we need anything further." },
          { speaker: "Denise", text: "Of course. Anything for Poppy. I'd like to stop for today, if that's all right." },
        ],
      },
    },
    {
      id: "transcript-frank",
      category: "transcript",
      title: "Interrogation — Frank Whitfield",
      subtitle: "Amy's father, hosting parent",
      date: "May 24, 1987",
      transcript: {
        subject: "Frank Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Where were you between five and six-thirty, Mr. Whitfield?" },
          { speaker: "Frank", text: "On the front lawn the whole time, filming with my new camcorder. Got the whole thing on tape, actually, if you want it. Got a Prodigy subscription too now, whole family's very modern." },
          { speaker: "Okafor", text: "We'll take the tape, thank you. And your wife — where was she during that window?" },
          { speaker: "Frank", text: "In and out. She popped out around six to grab a few things for after — she does that, she likes everything to be perfect for company. Denise takes hosting very seriously." },
          { speaker: "Okafor", text: "Grab a few things — from where, specifically?" },
          { speaker: "Frank", text: "I assumed Rusty's, that's where she always gets those potato skins. She wasn't gone long. Fifteen, twenty minutes, tops." },
          { speaker: "Okafor", text: "Did she mention anything unusual when she got back? Seem shaken, upset?" },
          { speaker: "Frank", text: "Honestly I had the camcorder up to my face the whole time, I wasn't paying close attention. She seemed a little flustered, but it was a big night, everybody was flustered." },
          { speaker: "Okafor", text: "How would you describe your wife's relationship with Poppy?" },
          { speaker: "Frank", text: "Fond of her, same as any of Amy's friends. Denise gets invested in these things, prom, pageants, that sort of thing — she was queen back in her day, you know, never lets us forget it, ha. But fond, genuinely fond." },
          { speaker: "Okafor", text: "One last thing — did you notice the Buick's position in the driveway change at all that evening?" },
          { speaker: "Frank", text: "Can't say I paid attention to that either. I was filming the lawn, not the driveway. You'd have to ask Denise." },
        ],
      },
    },
    {
      id: "transcript-amy",
      category: "transcript",
      title: "Interrogation — Amy Whitfield",
      subtitle: "Poppy's best friend",
      date: "May 24, 1987",
      transcript: {
        subject: "Amy Whitfield",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "How was Poppy seeming this week, anything unusual?" },
          { speaker: "Amy", text: "No, she was just excited. We all were. I keep thinking about our messages from Monday, we were just talking about dresses." },
          { speaker: "Okafor", text: "You two were both up for prom queen tonight. Was there any tension about that?" },
          { speaker: "Amy", text: "No! God, no. I mean, we both said we wanted it, but it was a joke, kind of. We weren't going to let a stupid crown mess up our friendship. I don't even care that much, I just — I said it because my mom would've loved it." },
          { speaker: "Okafor", text: "And your mother, that evening — walk me through it." },
          { speaker: "Amy", text: "She was really stressed about hosting, more than usual. She snapped at me for messing up the food table right before everyone got there. Then she disappeared for a bit and came back kind of pale, but she gets like that when she's stressed hosting." },
          { speaker: "Okafor", text: "Do you know where she went?" },
          { speaker: "Amy", text: "I figured the store. I don't know, I was busy getting my hair right." },
          { speaker: "Okafor", text: "How long was she gone, would you say?" },
          { speaker: "Amy", text: "Fifteen minutes? Twenty? I wasn't really watching the clock, I was more worried about Poppy not showing up. It didn't seem like a big deal at the time." },
          { speaker: "Okafor", text: "Anything different about your mom when she came back — her mood, how she was acting?" },
          { speaker: "Amy", text: "She was quiet. Really quiet, for her. My mom is never quiet. She just kind of got the drinks going and didn't say much until my dad asked her something. I thought maybe she was embarrassed the limo guy was waiting on her." },
          { speaker: "Okafor", text: "Is there anything else you remember from that night that felt off, even something small?" },
          { speaker: "Amy", text: "I keep thinking about it and I don't — I don't want to say something that isn't fair to her. She's my mom. Can I go now?" },
        ],
      },
    },
    {
      id: "transcript-jake",
      category: "transcript",
      title: "Interrogation — Jake Sorensen",
      subtitle: "Poppy's boyfriend",
      date: "May 24, 1987",
      transcript: {
        subject: "Jake Sorensen",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "What time did you get to the Whitfields'?" },
          { speaker: "Jake", text: "5:50, maybe a couple minutes before. I have three witnesses, we were all just standing around waiting." },
          { speaker: "Okafor", text: "Did you leave at any point, for any reason?" },
          { speaker: "Jake", text: "No, never. I was there the whole time, ask anybody." },
          { speaker: "Okafor", text: "How long have you and Poppy been together?" },
          { speaker: "Jake", text: "Since sophomore year. Almost two years. I had her corsage picked out weeks ago, the peach one, I wanted it to match exactly." },
          { speaker: "Okafor", text: "Did anything seem different about her lately? Any arguments, anyone bothering her?" },
          { speaker: "Jake", text: "No, nothing like that. Everybody loved Poppy. She was excited about tonight, about maybe winning queen, but she wasn't like, obsessed with it or anything. It was just fun for her." },
          { speaker: "Okafor", text: "Did you notice anything about the Whitfield house when you got there — anyone acting strange?" },
          { speaker: "Jake", text: "Not really, I was just watching the road for Poppy the whole time. Mrs. Whitfield seemed busy in and out of the house, but it's her house, she's hosting, that's normal, right?" },
          { speaker: "Okafor", text: "Is there anything else you can think of, even something that seemed small at the time?" },
          { speaker: "Jake", text: "I keep thinking if I'd walked over and met her partway none of this would've happened. I keep going over it and I can't — I just want to know what happened to her." },
        ],
      },
    },
    {
      id: "transcript-traci",
      category: "transcript",
      title: "Interrogation — Traci Nguyen",
      subtitle: "Poppy's best friend",
      date: "May 24, 1987",
      transcript: {
        subject: "Traci Nguyen",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "You're the yearbook photo editor, is that right? You notice details." },
          { speaker: "Traci", text: "Yeah, I guess. I was actually the one taking most of the pictures that night since Poppy wasn't there to be in them, ironically." },
          { speaker: "Okafor", text: "Anything odd about the Whitfield house that evening?" },
          { speaker: "Traci", text: "Mrs. Whitfield seemed really on edge, more than a hosting-a-party kind of on edge. She kept checking the driveway. And when she came back from wherever she went, her hands were shaking pouring the drinks later. I didn't think anything of it at the time." },
          { speaker: "Okafor", text: "You said 'came back' — did you actually see her leave, or just notice she wasn't there?" },
          { speaker: "Traci", text: "I didn't see her leave, I just remember looking around at one point for a place to set my camera bag down and she wasn't in the kitchen or the living room. Then a while later she was just back, kind of breathless." },
          { speaker: "Okafor", text: "Do you have a rough sense of how long she was gone?" },
          { speaker: "Traci", text: "Not really, sorry. I was more focused on Poppy not being there. Everyone kept asking me if I'd texted her, if I'd heard anything." },
          { speaker: "Okafor", text: "Anything else stand out, even something minor?" },
          { speaker: "Traci", text: "Just that the whole vibe of the night flipped. One minute we're all excited about pictures, the next everyone's freaking out. I have some photos from earlier if that helps, before things got bad." },
        ],
      },
    },
    {
      id: "transcript-marcus",
      category: "transcript",
      title: "Interrogation — Marcus Webb",
      subtitle: "Traci's date",
      date: "May 24, 1987",
      transcript: {
        subject: "Marcus Webb",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Where were you the whole evening?" },
          { speaker: "Marcus", text: "Whitfields' driveway, with Jake and Ben, waiting on the girls to finish getting ready. Nothing unusual until Poppy didn't show." },
          { speaker: "Okafor", text: "Was Jake with you the entire time, no gaps?" },
          { speaker: "Marcus", text: "The whole time, yeah. We were talking about the game Friday, then about work, killing time. He never went anywhere." },
          { speaker: "Okafor", text: "Did you notice Mrs. Whitfield at all that evening?" },
          { speaker: "Marcus", text: "A little. She came out at one point to tell the limo driver something, seemed stressed, but I figured that's just what happens when you're hosting a bunch of teenagers. Didn't think twice about it." },
          { speaker: "Okafor", text: "Anything unusual about the cars in the driveway?" },
          { speaker: "Marcus", text: "Not that I noticed, honestly. I wasn't really looking at cars, I was looking at my watch waiting for Traci to come down." },
        ],
      },
    },
    {
      id: "transcript-ben",
      category: "transcript",
      title: "Interrogation — Ben Cole",
      subtitle: "Amy's date",
      date: "May 24, 1987",
      transcript: {
        subject: "Ben Cole",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "You're new to Ridgeview — did you know Poppy well?" },
          { speaker: "Ben", text: "Not really, only through Amy. I mostly just remember Mrs. Whitfield seemed stressed all night, but I figured that's just what moms are like hosting stuff like this." },
          { speaker: "Okafor", text: "How long have you and Amy been dating?" },
          { speaker: "Ben", text: "A couple months. This was kind of a big deal, meeting all her friends and her parents properly. I was mostly just nervous about making a good impression, honestly, I wasn't paying attention to much else." },
          { speaker: "Okafor", text: "Did you see Mrs. Whitfield leave the house at any point?" },
          { speaker: "Ben", text: "I don't think so, but I really don't know my way around that house or that family yet, so I might've just missed it. I was mostly standing around trying not to say anything dumb to Amy's dad." },
          { speaker: "Okafor", text: "Anything strike you as unusual, even something small, looking back?" },
          { speaker: "Ben", text: "Not really. Everyone was on edge once Poppy didn't show, but before that it just seemed like a normal, kind of awkward family thing. Sorry, I wish I had more for you." },
        ],
      },
    },
    {
      id: "transcript-lou",
      category: "transcript",
      title: "Interrogation — Lou Griggs",
      subtitle: "Limo driver, Griggs Livery",
      date: "May 24, 1987",
      transcript: {
        subject: "Lou Griggs",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "How long have you been driving for Griggs Livery?" },
          { speaker: "Lou", text: "Eleven years. Prom season's my busiest stretch, I probably do fifteen, twenty pickups a weekend this time of year." },
          { speaker: "Okafor", text: "What time did you arrive at the Whitfield house?" },
          { speaker: "Lou", text: "6:25, right on schedule. Sat in that driveway near an hour before anybody said a word to me about what was going on." },
          { speaker: "Okafor", text: "Notice anything odd when you pulled up?" },
          { speaker: "Lou", text: "Just that the lady of the house wasn't around when I first pulled up. She came out to apologize for the wait maybe ten minutes after I got there, said she'd just been finishing up in the kitchen." },
          { speaker: "Okafor", text: "Did you happen to notice any other cars on the road on your way in, around Elm or Culvert Road?" },
          { speaker: "Lou", text: "I come in off Route 9, not through there, so no, can't help you there. I do this drive so often I could do it with my eyes closed." },
          { speaker: "Okafor", text: "Anything else about that evening stand out to you?" },
          { speaker: "Lou", text: "Just how long everybody waited around before it turned into something serious. Nobody wanted to say the word 'missing' out loud for a while, you could feel it. Real shame, sweet kids, all dressed up for nothing." },
        ],
      },
    },
    {
      id: "transcript-hallorans",
      category: "transcript",
      title: "Interrogation — Carol & Richard Halloran",
      subtitle: "Poppy's parents",
      date: "May 24, 1987",
      transcript: {
        subject: "Carol & Richard Halloran",
        interviewer: "Det. R. Okafor, Ridgeview PD",
        lines: [
          { speaker: "Okafor", text: "Take me through your daughter's last known movements, from your side." },
          { speaker: "Carol", text: "She left our house at 5:45 sharp, I have the photo timestamped. It's a fifteen minute walk to the Whitfields', she'd done it a hundred times, that whole route, she knew it like the back of her hand." },
          { speaker: "Richard", text: "We got there at 6:15 to help set up for the limo and she still wasn't there. Denise seemed distracted when she let us in, kept saying it wasn't like Poppy to be late." },
          { speaker: "Okafor", text: "Did Poppy have any reason to take a different route that evening, or stop anywhere along the way?" },
          { speaker: "Carol", text: "None that I know of. She was so excited, she wanted to get there early, she'd been talking about tonight for weeks. She wouldn't have wandered off." },
          { speaker: "Richard", text: "She wasn't the type to just not show up somewhere. If she was going to be late she'd call. That's what scared us the second we realized how much time had passed." },
          { speaker: "Okafor", text: "How would you describe the Whitfields, and your relationship with them?" },
          { speaker: "Carol", text: "We've known Denise and Frank for years, since the girls were little. Denise can be a lot — very particular about things being perfect — but she loves those kids. I never would have imagined anything like this touching that family." },
          { speaker: "Okafor", text: "Is there anything else, however small, that's stuck with you since that night?" },
          { speaker: "Richard", text: "Just Denise's face when we walked in. I keep thinking about it. I told myself at the time it was just stress from hosting. Now I don't know what to think." },
        ],
      },
    },
  ],
  solutionCharacterId: "denise",
  solutionSummary:
    "It was Denise Whitfield. She left the house around 5:48 to pick up potato skins from Rusty's — and passed Poppy walking up 4th Street. Denise had just overheard, in the group thread the parents didn't know the kids could see, that Poppy hoped to win prom queen — the one title Denise still measured her own daughter against. In a moment of blind jealousy on Poppy's behalf of a crown that hadn't even been awarded yet, Denise swerved onto the shoulder as she passed her, striking Poppy and killing her. She panicked, drove on to Rusty's as if nothing happened to establish her alibi, came home, plated the potato skins she'd already bought, and told police she'd never left the kitchen. The station wagon in the traffic-cam frame, the tire track at the crime scene, the potato skins in the background of the prom photos she claimed she 'didn't have time' to make, and her own contradicted alibi all place her on Culvert Road at 5:50pm — two minutes after Poppy was last seen alive.",
};
